---
title: "Computational Speed Comparison with South"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(LaplacesDemon)
library(BayesLogit) 
library(Matrix)
library(tidyverse)
```


Load Data 

```{r warning=FALSE}
load("data/data_multi-state/data.RDA")

#data 
covs = c("degree", "assistance", "no_car", "povPerc",  
         "white", "black", "native", "asian", "hispanic")
X <- model.matrix(~., all_data[, covs, drop=F]) 
n <- nrow(X); j <- ncol(X) # number of covariates INCLUDES intercept 

#response (with transformation)
y <- all_data$rentBurden
d.var <- all_data$rentBurdenSE^2
y.star <- log(y)
d.star <- d.var / y^2
```


Load Samplers

```{r}
source("test_speed_new/fh_fit.R")
source("test_speed_new/dm_fit.R")
source("test_speed_new/bym_fit.R")
source("test_speed_new/ssd_fit.R")
```

Run samplers (see time printed)

```{r}
set.seed(7)
# ---- Run Chains ----
# fit FH
fh_res <- fh_fit(X, y.star, d.star, ndesired=2500, nburn=10000, nthin=1)
# fit DM
dm_res <- dm_fit(X, y.star, d.star, ndesired=2500, nburn=10000, nthin=1)
# fit BYM
bym_res <- bym_fit(X, y.star, d.star, A, ndesired=2500, nburn=1500, nthin=1)
# fit SSD
new_res <- ssd_fit(X, y.star, d.star, A, ndesired=2500, nburn=1500, nthin=1)
```

How many minutes?

```{r}
1986.150/60
3493.779/60
```



```{r}
# save(fh_res, file="fh_res.RDA")
# save(dm_res, file="dm_res.RDA")
# save(bym_res, file="bym_res.RDA")
# save(new_res, file="new_res.RDA")
```

